### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by mert574** [DoctorMcKay/Trade-Offer-Single-Click#1]
Installed on chrome as extension. I can see it is active on extensions page, i've restarted chrome but the script is not working. I also installed "yes this is a gift" extension but both are the same. Are these scripts still working?

Steam Inventory Helper is installed.

I don't know how to provide any log or something else about this problem.

Using Chrome 51.0.2704.84 m (64-bit)

Edit:
Updated Chrome to 51.0.2704.103 m (64-bit) AND Disabled Steam Inventory Helper but still same.

Edit2:
When I copy & paste the "yes this is a gift" script to the console on tradeoffer page, it is working. But the single-click one is not working.

So I'm thinking, i've installed these wrong. I've just dragged and dropped to the chrome extensions page.

**Comment by mert574** [comment]
Do not install as chrome extension. Use tampermonkey; scripts are still working.

**Comment by PredatorIWD** [comment]
@mert574 I would recommend [reading this](https://stackoverflow.com/questions/9515704/insert-code-into-the-page-context-using-a-content-script) to understand why did it work when you pasted it in the console, and didnt in your content script.
